import { 
  ReportListItem, 
  DashboardKPIData, 
  DailyActivityData 
} from '@/lib/reports-data';

export const INITIAL_DASHBOARD_KPI: DashboardKPIData = {
  totalInspections: {
    value: 1428,
    change: 12.4,
    period: 'vs last month',
  },
  passRate: {
    value: 86.4,
    change: 3.2,
    period: 'vs last month',
  },
  pendingDrafts: {
    value: 14,
    urgentCount: 3,
  },
  flaggedDefects: {
    value: 28,
    tamperedCount: 4,
  },
  activeInspectors: {
    total: 10,
    onDuty: 8,
  },
};

export const WEEKLY_ACTIVITY_DATA: DailyActivityData[] = [
  { day: 'Mon', date: 'Aug 01', passed: 18, failed: 4, total: 22 },
  { day: 'Tue', date: 'Aug 02', passed: 24, failed: 3, total: 27 },
  { day: 'Wed', date: 'Aug 03', passed: 21, failed: 6, total: 27 },
  { day: 'Thu', date: 'Aug 04', passed: 28, failed: 5, total: 33 },
  { day: 'Fri', date: 'Aug 05', passed: 32, failed: 4, total: 36 },
  { day: 'Sat', date: 'Aug 06', passed: 35, failed: 8, total: 43 },
  { day: 'Sun', date: 'Aug 07', passed: 15, failed: 2, total: 17 },
];

export const INSPECTION_TYPE_BREAKDOWN = [
  { label: '600-Points Comprehensive', count: 742, percentage: 52, color: '#9723FF' },
  { label: 'Pre-Purchase Inspection', count: 386, percentage: 27, color: '#008751' },
  { label: '300-Points Standard', count: 214, percentage: 15, color: '#5368FF' },
  { label: 'Chassis & Drivetrain Only', count: 86, percentage: 6, color: '#FE8E4B' },
];

export const INITIAL_REPORTS_LIST: ReportListItem[] = [
  {
    id: '440',
    reportNumber: 'ORB-440',
    vehicle: {
      make: 'Toyota',
      model: 'Tundra TRD Pro',
      year: 2025,
      type: 'Truck',
      color: 'Magnetic Grey',
      colorHex: '#646669',
      imageUrl: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&q=80&w=600',
      vin: 'WMWWG9C51K3E40764',
      odometer: '621,515 KM',
      odometerStatus: 'Tampered',
      transmission: 'Automatic 10-Speed',
      specs: 'American Specs',
    },
    client: {
      name: 'Al Tayer Motors LLC',
      company: 'Al Tayer Fleet Services',
      location: 'Dubai',
      phone: '+971 054 409 3009',
      email: 'fleet@altayer.com',
    },
    inspector: {
      id: 'ins-1',
      name: 'Ahmed Al Mansoori',
      avatarUrl: 'https://i.pravatar.cc/150?u=ahmed_mansoori',
      badge: 'Lead Master Inspector',
    },
    date: '06 Aug 2025',
    time: '09:00 PM',
    inspectionType: '600-Points Comprehensive',
    passPercentage: 55,
    failPercentage: 45,
    status: 'published',
    flaggedDefectsCount: 6,
    lastUpdated: 'Saved 2m ago',
  },
  {
    id: '439',
    reportNumber: 'ORB-439',
    vehicle: {
      make: 'Porsche',
      model: '911 GT3 (992)',
      year: 2024,
      type: 'Sports',
      color: 'Shark Blue',
      colorHex: '#1E64C8',
      imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=600',
      vin: 'WP0AF2A97NS284910',
      odometer: '8,420 KM',
      odometerStatus: 'Normal',
      transmission: 'PDK 7-Speed',
      specs: 'GCC Specs',
    },
    client: {
      name: 'Ali & Sons Luxury Cars',
      company: 'Ali & Sons Holding',
      location: 'Abu Dhabi',
      phone: '+971 050 312 8899',
      email: 'vip.concierge@ali-sons.ae',
    },
    inspector: {
      id: 'ins-2',
      name: 'David Miller',
      avatarUrl: 'https://i.pravatar.cc/150?u=david_miller',
      badge: 'Senior Chassis Specialist',
    },
    date: '06 Aug 2025',
    time: '04:30 PM',
    inspectionType: '600-Points Comprehensive',
    passPercentage: 98,
    failPercentage: 2,
    status: 'published',
    flaggedDefectsCount: 0,
    lastUpdated: '1 hour ago',
  },
  {
    id: '438',
    reportNumber: 'ORB-438',
    vehicle: {
      make: 'Land Rover',
      model: 'Defender 110 V8',
      year: 2024,
      type: 'SUV',
      color: 'Santorini Black',
      colorHex: '#1A1A1A',
      imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&q=80&w=600',
      vin: 'SALWR2V48PA109283',
      odometer: '34,120 KM',
      odometerStatus: 'Normal',
      transmission: 'Automatic 8-Speed',
      specs: 'GCC Specs',
    },
    client: {
      name: 'Mohamed Bin Rashid Cars',
      company: 'Al Habtoor Motors',
      location: 'Dubai',
      phone: '+971 055 882 1199',
      email: 'prestige@habtoor.ae',
    },
    inspector: {
      id: 'ins-3',
      name: 'Rashid Khan',
      avatarUrl: 'https://i.pravatar.cc/150?u=rashid_khan',
      badge: 'Certified Diagnostic Tech',
    },
    date: '05 Aug 2025',
    time: '11:15 AM',
    inspectionType: '300-Points Standard',
    passPercentage: 88,
    failPercentage: 12,
    status: 'published',
    flaggedDefectsCount: 2,
    lastUpdated: 'Yesterday',
  },
  {
    id: '437',
    reportNumber: 'ORB-437',
    vehicle: {
      make: 'Mercedes-Benz',
      model: 'G63 AMG 4x4²',
      year: 2023,
      type: 'SUV',
      color: 'G Manufaktur Olive',
      colorHex: '#525948',
      imageUrl: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&q=80&w=600',
      vin: 'W1N4632761X392819',
      odometer: '19,850 KM',
      odometerStatus: 'Normal',
      transmission: 'AMG SPEEDSHIFT 9G',
      specs: 'GCC Specs',
    },
    client: {
      name: 'Gargash Enterprises',
      company: 'Gargash Mercedes VIP',
      location: 'Sharjah',
      phone: '+971 052 991 4455',
      email: 'vip.sales@gargash.ae',
    },
    inspector: {
      id: 'ins-1',
      name: 'Ahmed Al Mansoori',
      avatarUrl: 'https://i.pravatar.cc/150?u=ahmed_mansoori',
      badge: 'Lead Master Inspector',
    },
    date: '04 Aug 2025',
    time: '02:00 PM',
    inspectionType: '600-Points Comprehensive',
    passPercentage: 91,
    failPercentage: 9,
    status: 'published',
    flaggedDefectsCount: 1,
    lastUpdated: '2 days ago',
  },
  {
    id: '436',
    reportNumber: 'ORB-436',
    vehicle: {
      make: 'BMW',
      model: 'M4 Competition (G82)',
      year: 2023,
      type: 'Coupe',
      color: 'Isle of Man Green',
      colorHex: '#1B4D3E',
      imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=600',
      vin: 'WBA33AY07PFP09281',
      odometer: '45,200 KM',
      odometerStatus: 'Replaced',
      transmission: 'M Steptronic 8-Speed',
      specs: 'American Specs',
    },
    client: {
      name: 'AGMC BMW Certified',
      company: 'AGMC Motors',
      location: 'Dubai',
      phone: '+971 050 442 8181',
      email: 'service.booking@agmc.ae',
    },
    inspector: {
      id: 'ins-4',
      name: 'Sarah Jenkins',
      avatarUrl: 'https://i.pravatar.cc/150?u=sarah_jenkins',
      badge: 'Electrical & ECM Specialist',
    },
    date: '03 Aug 2025',
    time: '10:45 AM',
    inspectionType: 'Pre-Purchase Inspection',
    passPercentage: 74,
    failPercentage: 26,
    status: 'draft',
    flaggedDefectsCount: 4,
    lastUpdated: '3 days ago',
  },
  {
    id: '435',
    reportNumber: 'ORB-435',
    vehicle: {
      make: 'Nissan',
      model: 'Patrol NISMO V8',
      year: 2024,
      type: 'SUV',
      color: 'White Pearl',
      colorHex: '#F0EFEA',
      imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600',
      vin: 'JN8AY2NY1P9028172',
      odometer: '12,400 KM',
      odometerStatus: 'Normal',
      transmission: 'Automatic 7-Speed',
      specs: 'GCC Specs',
    },
    client: {
      name: 'Arabian Automobiles Co.',
      company: 'Rostamani Group',
      location: 'Dubai',
      phone: '+971 056 112 3444',
      email: 'fleet@arabianautomobiles.com',
    },
    inspector: {
      id: 'ins-2',
      name: 'David Miller',
      avatarUrl: 'https://i.pravatar.cc/150?u=david_miller',
      badge: 'Senior Chassis Specialist',
    },
    date: '02 Aug 2025',
    time: '03:15 PM',
    inspectionType: 'Chassis & Drivetrain',
    passPercentage: 95,
    failPercentage: 5,
    status: 'published',
    flaggedDefectsCount: 1,
    lastUpdated: '4 days ago',
  },
  {
    id: '434',
    reportNumber: 'ORB-434',
    vehicle: {
      make: 'Ford',
      model: 'F-150 Raptor R',
      year: 2023,
      type: 'Truck',
      color: 'Code Orange',
      colorHex: '#D35400',
      imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=600',
      vin: '1FTFW1RJ8PFC82716',
      odometer: '104,800 KM',
      odometerStatus: 'Tampered',
      transmission: 'SelectShift 10-Speed',
      specs: 'American Specs',
    },
    client: {
      name: 'Desert Motors Trading',
      company: 'Desert 4x4 Exotics',
      location: 'Sharjah',
      phone: '+971 050 771 9900',
      email: 'sales@desertmotors.ae',
    },
    inspector: {
      id: 'ins-1',
      name: 'Ahmed Al Mansoori',
      avatarUrl: 'https://i.pravatar.cc/150?u=ahmed_mansoori',
      badge: 'Lead Master Inspector',
    },
    date: '01 Aug 2025',
    time: '05:30 PM',
    inspectionType: '600-Points Comprehensive',
    passPercentage: 42,
    failPercentage: 58,
    status: 'draft',
    flaggedDefectsCount: 8,
    lastUpdated: '5 days ago',
  },
  {
    id: '433',
    reportNumber: 'ORB-433',
    vehicle: {
      make: 'Audi',
      model: 'RS6 Avant Performance',
      year: 2024,
      type: 'Sedan',
      color: 'Nardo Grey',
      colorHex: '#808284',
      imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=600',
      vin: 'WAUZZZF23PA091823',
      odometer: '14,350 KM',
      odometerStatus: 'Normal',
      transmission: 'Tiptronic 8-Speed',
      specs: 'GCC Specs',
    },
    client: {
      name: 'Ali & Sons Luxury Cars',
      company: 'Ali & Sons Holding',
      location: 'Abu Dhabi',
      phone: '+971 050 312 8899',
      email: 'vip.concierge@ali-sons.ae',
    },
    inspector: {
      id: 'ins-3',
      name: 'Rashid Khan',
      avatarUrl: 'https://i.pravatar.cc/150?u=rashid_khan',
      badge: 'Certified Diagnostic Tech',
    },
    date: '31 Jul 2025',
    time: '01:00 PM',
    inspectionType: 'Pre-Purchase Inspection',
    passPercentage: 96,
    failPercentage: 4,
    status: 'published',
    flaggedDefectsCount: 0,
    lastUpdated: '6 days ago',
  },
];

// Aliases for seamless backward compatibility
export const initialDashboardKPI = INITIAL_DASHBOARD_KPI;
export const weeklyActivityData = WEEKLY_ACTIVITY_DATA;
export const inspectionTypeBreakdown = INSPECTION_TYPE_BREAKDOWN;
export const initialReportsList = INITIAL_REPORTS_LIST;
