export interface ColorOption {
  label: string;
  value: string;
  hex: string;
  border?: string;
}

export const CAR_MAKES: readonly string[] = [
  'Toyota',
  'Nissan',
  'Ford',
  'BMW',
  'Mercedes-Benz',
  'Lexus',
  'Land Rover',
  'Porsche',
  'GMC',
  'Chevrolet',
  'Dodge',
  'Jeep',
  'Audi',
  'Hyundai',
  'Kia',
  'Honda',
  'Volkswagen',
  'Tesla',
  'Mazda',
  'Mitsubishi',
  'Ferrari',
  'Lamborghini',
  'Rolls-Royce',
  'Bentley',
  'Aston Martin',
  'Maserati',
  'Genesis',
  'Volvo',
  'Jaguar',
  'Cadillac',
  'Lincoln',
  'Subaru',
  'Mini',
  'Suzuki',
  'Jetour',
  'Haval',
  'BYD',
  'MG',
  'Changan',
  'Geely',
  'Chery',
  'Infiniti',
  'Acura',
  'Alfa Romeo',
  'Peugeot',
  'Renault',
  'Ram',
  'Lucid',
  'Rivian',
  'Polestar',
] as const;

export const CAR_MODELS_BY_MAKE: Record<string, readonly string[]> = {
  Toyota: [
    'Tundra',
    'Land Cruiser',
    'Land Cruiser Prado',
    'Camry',
    'Corolla',
    'RAV4',
    'Fortuner',
    'Hilux',
    'Highlander',
    'Crown',
    'Supra',
    'Yaris',
    '4Runner',
    'Sequoia',
    'Sienna',
    'Tacoma',
    'FJ Cruiser',
    'Granvia',
    'Urban Cruiser',
    'Raize',
    'Innova',
    'Avanza',
    'C-HR',
  ],
  Nissan: [
    'Patrol',
    'Patrol Super Safari',
    'Altima',
    'Sunny',
    'X-Trail',
    'Pathfinder',
    'Maxima',
    'Navara',
    'GT-R',
    'Kicks',
    'Armada',
    'Urvan',
    'Murano',
    'Sentra',
    'Z',
    '370Z',
    'X-Terra',
    'Juke',
  ],
  Ford: [
    'F-150',
    'Explorer',
    'Mustang',
    'Expedition',
    'Bronco',
    'Bronco Sport',
    'Ranger',
    'Edge',
    'Everest',
    'Taurus',
    'Territory',
    'F-250 Super Duty',
    'F-350 Super Duty',
    'Transit',
    'Escape',
  ],
  BMW: [
    '3 Series',
    '4 Series',
    '5 Series',
    '7 Series',
    '8 Series',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'XM',
    'M2',
    'M3',
    'M4',
    'M5',
    'M8',
    'i4',
    'i7',
    'iX',
    'iX3',
    'Z4',
  ],
  'Mercedes-Benz': [
    'G-Class (G 63 AMG)',
    'C-Class',
    'E-Class',
    'S-Class',
    'GLE',
    'GLC',
    'GLS',
    'GLA',
    'GLB',
    'CLA',
    'CLS',
    'A-Class',
    'AMG GT',
    'SL-Class',
    'Maybach S-Class',
    'Maybach GLS',
    'EQS',
    'EQE',
    'EQA',
    'V-Class',
    'Sprinter',
  ],
  Lexus: [
    'LX 600',
    'LX 570',
    'GX 460',
    'GX 550',
    'RX 350',
    'RX 500h',
    'ES 350',
    'ES 300h',
    'IS 350',
    'IS 300',
    'NX 350',
    'TX',
    'UX 200',
    'LC 500',
    'LS 500',
    'RC F',
  ],
  'Land Rover': [
    'Range Rover',
    'Range Rover Sport',
    'Range Rover Velar',
    'Range Rover Evoque',
    'Defender 90',
    'Defender 110',
    'Defender 130',
    'Discovery',
    'Discovery Sport',
  ],
  Porsche: [
    '911 Carrera',
    '911 Turbo',
    '911 GT3',
    'Cayenne',
    'Cayenne Coupe',
    'Macan',
    'Macan EV',
    'Panamera',
    'Taycan',
    '718 Cayman',
    '718 Boxster',
  ],
  GMC: [
    'Sierra 1500',
    'Sierra HD',
    'Sierra Denali',
    'Yukon',
    'Yukon XL',
    'Yukon Denali',
    'Terrain',
    'Acadia',
    'Canyon',
    'Hummer EV',
  ],
  Chevrolet: [
    'Tahoe',
    'Suburban',
    'Silverado 1500',
    'Silverado HD',
    'Corvette Stingray',
    'Corvette Z06',
    'Camaro',
    'Captiva',
    'Traverse',
    'Blazer',
    'Trailblazer',
    'Groove',
    'Malibu',
    'Express',
  ],
  Dodge: [
    'Charger',
    'Challenger',
    'Durango',
    'Durango SRT Hellcat',
    'RAM 1500',
    'RAM 2500',
    'RAM TRX',
  ],
  Jeep: [
    'Wrangler',
    'Wrangler Rubicon',
    'Grand Cherokee',
    'Grand Cherokee L',
    'Gladiator',
    'Wagoneer',
    'Grand Wagoneer',
    'Cherokee',
    'Compass',
    'Renegade',
  ],
  Audi: [
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'RS3',
    'RS6 Avant',
    'RS7',
    'RSQ8',
    'e-tron GT',
    'Q8 e-tron',
    'R8',
  ],
  Hyundai: [
    'Tucson',
    'Santa Fe',
    'Sonata',
    'Elantra',
    'Palisade',
    'Creta',
    'Accent',
    'Kona',
    'Venue',
    'Staria',
    'Ioniq 5',
    'Ioniq 6',
    'Azera',
  ],
  Kia: [
    'Sportage',
    'Sorento',
    'Telluride',
    'K5',
    'Carnival',
    'Cerato',
    'Seltos',
    'Pegas',
    'Sonet',
    'Stinger',
    'EV6',
    'EV9',
    'Cadenza',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'HR-V',
    'City',
    'Odyssey',
    'ZR-V',
    'Jazz',
  ],
  Volkswagen: [
    'Golf',
    'Golf GTI',
    'Golf R',
    'Tiguan',
    'Touareg',
    'Teramont',
    'Passat',
    'T-Roc',
    'ID.4',
    'Arteon',
    'Polo',
  ],
  Tesla: [
    'Model 3',
    'Model Y',
    'Model S',
    'Model X',
    'Cybertruck',
  ],
  Mazda: [
    'CX-5',
    'CX-9',
    'CX-60',
    'CX-90',
    'CX-30',
    'Mazda 3',
    'Mazda 6',
    'MX-5 Miata',
  ],
  Mitsubishi: [
    'Pajero',
    'Outlander',
    'Montero Sport',
    'L200',
    'Eclipse Cross',
    'ASX',
    'Attrage',
    'Xpander',
  ],
  Ferrari: [
    '488 GTB',
    'F8 Tributo',
    'Roma',
    '296 GTB',
    'SF90 Stradale',
    '812 Superfast',
    'Purosangue',
    'Portofino M',
    '12Cilindri',
  ],
  Lamborghini: [
    'Urus',
    'Urus Performante',
    'Huracán',
    'Huracán STO',
    'Revuelto',
    'Aventador',
  ],
  'Rolls-Royce': [
    'Cullinan',
    'Ghost',
    'Phantom',
    'Spectre',
    'Wraith',
    'Dawn',
  ],
  Bentley: [
    'Continental GT',
    'Bentayga',
    'Flying Spur',
  ],
  'Aston Martin': [
    'DBX',
    'DBX 707',
    'Vantage',
    'DB12',
    'DB11',
    'DBS Superleggera',
  ],
  Maserati: [
    'Levante',
    'Grecale',
    'Ghibli',
    'Quattroporte',
    'MC20',
    'GranTurismo',
  ],
  Genesis: [
    'G70',
    'G80',
    'G90',
    'GV70',
    'GV80',
    'Electrified GV70',
  ],
  Volvo: [
    'XC90',
    'XC60',
    'XC40',
    'S90',
    'S60',
    'EX90',
    'EX30',
  ],
  Jaguar: [
    'F-Pace',
    'E-Pace',
    'I-Pace',
    'F-Type',
    'XF',
  ],
  Cadillac: [
    'Escalade',
    'Escalade ESV',
    'CT4',
    'CT5',
    'XT4',
    'XT5',
    'XT6',
    'Lyriq',
  ],
  Lincoln: [
    'Navigator',
    'Aviator',
    'Nautilus',
    'Corsair',
  ],
  Subaru: [
    'WRX',
    'Outback',
    'Forester',
    'Crosstrek',
    'BRZ',
    'Ascent',
  ],
  Suzuki: [
    'Jimny',
    'Grand Vitara',
    'Swift',
    'Baleno',
    'Ertiga',
    'Ciaz',
    'Dzire',
  ],
  Jetour: [
    'T2',
    'Dashing',
    'X70 Plus',
    'X90 Plus',
  ],
  Haval: [
    'H6',
    'Jolion',
    'Dargo',
    'Tank 300',
    'Tank 500',
  ],
  BYD: [
    'Seal',
    'Han',
    'Tang',
    'Atto 3',
    'Song Plus',
    'Yangwang U8',
  ],
  MG: [
    'MG GT',
    'MG RX5',
    'MG HS',
    'MG ONE',
    'MG Whale',
    'MG ZS',
    'MG 4 EV',
  ],
  Changan: [
    'CS95',
    'CS85',
    'CS35 Plus',
    'UNI-K',
    'UNI-T',
    'UNI-V',
  ],
  Geely: [
    'Monjaro',
    'Coolray',
    'Tugella',
    'Emgrand',
    'Geometry C',
  ],
  Chery: [
    'Tiggo 8 Pro',
    'Tiggo 7 Pro',
    'Tiggo 4 Pro',
    'Arrizo 8',
  ],
  Ram: [
    '1500',
    '1500 TRX',
    '2500 Heavy Duty',
    '3500 Heavy Duty',
  ],
  Infiniti: [
    'QX80',
    'QX60',
    'QX55',
    'QX50',
    'Q50',
    'Q60',
  ],
};

export const POPULAR_CAR_MODELS: readonly string[] = [
  'Land Cruiser',
  'Patrol',
  'Tundra',
  'F-150',
  'Range Rover',
  'Sierra 1500',
  'Tahoe',
  'Yukon',
  'Defender 110',
  'Wrangler',
  'Prado',
  'Cayenne',
  'G-Class (G 63 AMG)',
  'X5',
  'Camry',
  'Altima',
  'Corolla',
  'RAV4',
  'Civic',
  'Model Y',
  'Model 3',
  'Jimny',
] as const;

export const REGIONAL_SPECS_OPTIONS: readonly string[] = [
  'GCC Specs',
  'American Specs',
  'Canadian Specs',
  'European Specs',
  'Japanese Specs',
  'Korean Specs',
  'Australian Specs',
  'Chinese Specs',
  'Other',
] as const;

export const TRANSMISSION_OPTIONS: readonly string[] = [
  'Automatic',
  'Manual',
  'CVT (Continuously Variable)',
  'Dual-Clutch (DCT / PDK)',
  'Automated Manual (AMT)',
  'Direct-Drive (EV Single-Speed)',
] as const;

export const ENGINE_SIZE_OPTIONS: readonly string[] = [
  '1.0L Turbo I3',
  '1.2L I4',
  '1.5L Turbo I4',
  '1.6L I4',
  '2.0L I4',
  '2.0L Turbo I4',
  '2.4L / 2.5L I4',
  '2.5L Hybrid',
  '3.0L Turbo I6',
  '3.0L Twin-Turbo V6',
  '3.5L V6',
  '3.5L Twin-Turbo V6',
  '3.8L V6',
  '4.0L V8',
  '4.0L Twin-Turbo V8',
  '4.4L Twin-Turbo V8',
  '4.6L / 4.7L V8',
  '5.0L V8',
  '5.3L V8',
  '5.6L V8',
  '5.7L V8',
  '6.0L V12',
  '6.2L V8',
  '6.2L Supercharged V8',
  '6.75L Twin-Turbo V12',
  'Electric Motor (Single)',
  'Dual Electric Motor (AWD)',
  'Tri-Motor AWD',
  'Quad-Motor AWD',
] as const;

export const VEHICLE_TYPE_OPTIONS: readonly string[] = [
  'SUV',
  'Sedan',
  'Truck',
  'Pickup',
  'Coupe',
  'Convertible',
  'Crossover',
  'Hatchback',
  'Van / Minivan',
  'Station Wagon',
  'Sports Car',
] as const;

export const EXTERNAL_COLOUR_OPTIONS: readonly ColorOption[] = [
  { label: 'White', value: 'White', hex: '#FFFFFF', border: '#E2E8F0' },
  { label: 'Pearl White', value: 'Pearl White', hex: '#FDFBF7', border: '#E2E8F0' },
  { label: 'Black', value: 'Black', hex: '#171717' },
  { label: 'Grey', value: 'Grey', hex: '#6B7280' },
  { label: 'Nardo Grey', value: 'Nardo Grey', hex: '#9CA3AF' },
  { label: 'Charcoal', value: 'Charcoal', hex: '#374151' },
  { label: 'Silver', value: 'Silver', hex: '#CBD5E1' },
  { label: 'Blue', value: 'Blue', hex: '#2563EB' },
  { label: 'Navy Blue', value: 'Navy Blue', hex: '#1E3A8A' },
  { label: 'Red', value: 'Red', hex: '#DC2626' },
  { label: 'Burgundy / Maroon', value: 'Burgundy', hex: '#831843' },
  { label: 'Brown', value: 'Brown', hex: '#78350F' },
  { label: 'Green', value: 'Green', hex: '#16A34A' },
  { label: 'Olive / Army Green', value: 'Olive Green', hex: '#4D7C0F' },
  { label: 'Gold', value: 'Gold', hex: '#D97706' },
  { label: 'Yellow', value: 'Yellow', hex: '#EAB308' },
  { label: 'Orange', value: 'Orange', hex: '#EA580C' },
  { label: 'Beige', value: 'Beige', hex: '#D4C5B9' },
  { label: 'Bronze', value: 'Bronze', hex: '#92400E' },
] as const;

export const FUEL_TYPE_OPTIONS: readonly string[] = [
  'Petrol',
  'Diesel',
  'Hybrid',
  'Plug-in Hybrid (PHEV)',
  'Electric (EV)',
  'Mild Hybrid (MHEV)',
  'Hydrogen (FCEV)',
] as const;
